- name: Install MySQL Package
  apt:
    update_cache: true
    name: mysql-server, python3-pymysql
    state: present
- name: Starting MySQL Service
  service:
    name: mysql
    state: started
    enabled: yes
- name: Create Wordpress Database
  mysql_db:
    login_unix_socket: "{{ db['mysql_sock'] }}"
    name: "{{ db['mysql_db_name'] }}"
    state: present
- name: Create Wordpress User
  mysql_user:
    check_implicit_admin: yes
    login_unix_socket: "{{ db['mysql_sock'] }}"
    name: "{{ db['mysql_user_name'] }}"
    password: "{{ db['mysql_user_passwd'] }}"
    host: "{{ private_ip }}"
    priv: wpdb.*:ALL,GRANT
    state: present
- name: External Connection Setting
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: bind-address
    line: bind-address=0.0.0.0
  notify: Restart MySQL services

