- name: Install Database in Debian
  import_tasks: db_debian.yaml
  when: ansible_facts['os_family'] == "Debian"

- name: Install Database in RedHat
  import_tasks: db_redhat.yaml
  when: ansible_facts['os_family'] == "RedHat"
